service: remessa-voice-api

frameworkVersion: '2.72.3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  currencyQuotes:
    handler: dist/main/handlers.currencyQuotes
    events:
      - httpApi: 'POST /quotes/currencies/{currencyId}'

plugins:
  - serverless-offline
